name: update-action-version-in-file

description: Updates each instance of the semantic version for an action in the specified file and optionally saves the changes to disk.

inputs:
  file-to-update:
    description: 'The name of the file that should be updated with the new action version.  Defaults to README.md.'
    required: true
  action-name:
    description: 'The name of the action.  Format should be org/repo and any nested directories if applicable.'
    required: true
  version-prefix:
    description: 'The prefix the action uses in its versions, if used.  Defaults to `v`.'
    default: 'v'
  updated-version:
    description: 'The new action version to replace other instances with in the specified file.'
    required: true

outputs:
  updated-content:
    description: 'The updated file content after replacements are made.'

runs:
  using: 'node16'
  main: 'dist/index.js'
